#!/bin/sh

if [ -e /var/clearos/marketplace/search_history.root ]; then
    logger -p local6.notice -t installer "app-marketplace-core - removing search history file"
    rm -f /var/clearos/marketplace/search_history.root
fi
